In [1]:
import pandas as pd
import numpy as np

In [4]:
datas = pd.date_range('20210101',periods=6)

df = pd.DataFrame(np.random.randn(6,4),index=datas, columns=['VAR_A', 'VAR_B', 'VAR_C', 'VAR_D'])
df

VAR_A     VAR_B     VAR_C     VAR_D
2021-01-01 -0.181082  1.160076  1.851111  0.123508
2021-01-02 -0.341774  0.207063 -0.262938  0.779615
2021-01-03 -0.758438 -0.234051 -0.461538  0.644414
2021-01-04 -0.033895 -1.841804 -0.713514  0.418642
2021-01-05 -0.079732 -0.825240  0.106678  0.176222
2021-01-06 -0.092236 -0.167255  1.112072  0.575803

In [5]:
dft = df.T

In [7]:
df.shape


(6, 4)

In [8]:
dft.shape

(4, 6)

In [10]:
dft.values

array([[-0.18108189, -0.34177363, -0.75843789, -0.03389503, -0.07973161,
        -0.09223609],
       [ 1.16007607,  0.20706269, -0.23405069, -1.84180446, -0.82524049,
        -0.16725484],
       [ 1.8511111 , -0.26293843, -0.46153824, -0.71351373,  0.1066778 ,
         1.1120723 ],
       [ 0.12350767,  0.77961496,  0.64441351,  0.41864176,  0.17622196,
         0.57580291]])

In [11]:
v = dft.values
v

array([[-0.18108189, -0.34177363, -0.75843789, -0.03389503, -0.07973161,
        -0.09223609],
       [ 1.16007607,  0.20706269, -0.23405069, -1.84180446, -0.82524049,
        -0.16725484],
       [ 1.8511111 , -0.26293843, -0.46153824, -0.71351373,  0.1066778 ,
         1.1120723 ],
       [ 0.12350767,  0.77961496,  0.64441351,  0.41864176,  0.17622196,
         0.57580291]])

In [12]:
v.reshape((2,12))

array([[-0.18108189, -0.34177363, -0.75843789, -0.03389503, -0.07973161,
        -0.09223609,  1.16007607,  0.20706269, -0.23405069, -1.84180446,
        -0.82524049, -0.16725484],
       [ 1.8511111 , -0.26293843, -0.46153824, -0.71351373,  0.1066778 ,
         1.1120723 ,  0.12350767,  0.77961496,  0.64441351,  0.41864176,
         0.17622196,  0.57580291]])